Conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', namespace='pages'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from common.views import *

app_name = 'pages'

urlpatterns = [
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('category/', category_page, name='category'),
<<<<<<< HEAD
    path('blog/', blog_page, name='blog'),
=======
>>>>>>> 031e4426d2755a8cbeb24e504ca6808c015cc87a
    path('recipe/', recipe_page, name='recipes'),
    path('', home_page),
]

blogs/models.py
from django.contrib.auth.models import User
from django.db import models

from common.models import BaseModel


class BlogCategoryModel(BaseModel):
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog category'
        verbose_name_plural = 'Blog categories'


class BlogTagModel(BaseModel):
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog tag'
        verbose_name_plural = 'Blog tags'


class BlogModel(BaseModel):
    title = models.CharField(max_length=128)
    image1 = models.ImageField(upload_to='blogs')
    image2 = models.ImageField(upload_to='blogs')
    short_description = models.CharField(max_length=255)
    long_description = models.TextField()

    categories = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='blogs')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog tag'
        verbose_name_plural = 'Blog tags'


class BlogCommentModel(BaseModel):
    comment = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_comment')
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = 'Blog comment'
        verbose_name_plural = 'Blog comments'


class BlogLikeModel(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_like')
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE, related_name='likes')

    def __str__(self):
        return f'{self.user.get_full_name()} liked to {self.blog}'

    class Meta:
        verbose_name = 'Blog tag'
        verbose_name_plural = 'Blog tags'












class Category(BaseModel):
    name = models.CharField(max_length=255)
    description = models.TextField()


    def __str__(self):
        return self.name

    def __repr__(self):
        return f'Category: {self.name}'


    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(BaseModel):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    in_stock = models.BooleanField(default=False)


    def __str__(self):
        return self.name

    def __repr__(self):
        return f'Product: {self.name}, Price: {self.price}'

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

common/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

blogs/views.py
from django.shortcuts import render

# Create your views here.

common/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'index.html')

def about_page(request):
    return render(request, 'pages/about.html')

def contact_page(request):
    return render(request, 'pages/contact.html')

def category_page(request):
    return render(request, 'recipes/category.html')

def recipe_page(request):
    return render(request, 'recipes/recipe-with-sidebar.html')

def blog_page(request):
    return render(request, 'blogs/blog-grid.html')

def submit_page(request):
    return render(request, 'recipes/submit-recipe.html')

def login_page(request):
    return render(request, 'auth/login.html')

templates/layouts/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Ranna | Home 1</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <!-- Normalize Css -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- Main Css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Bootstrap Css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="{% static 'fonts/flaticon.css' %}">
    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Modernizr Js -->
    <script src="{% static 'js/modernizr-3.6.0.min.js' %}"></script>
</head>

<body>
    <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->

    <!-- Add your site or application content here -->
    <!-- Preloader Start Here -->
    {% url 'pages:contact' as contact %}
    {% if request.path != contact %}
        <div id="preloader"></div>
    {% endif %}
    <!-- Preloader End Here -->
    <!-- ScrollUp Start Here -->
    <a href="#wrapper" data-type="section-switch" class="scrollup">
        <i class="fas fa-angle-double-up"></i>
    </a>
    <!-- ScrollUp End Here -->
    <div id="wrapper" class="wrapper">
        <!-- Header Area Start Here -->
        {% include 'layouts/header.html' %}
        <!-- Header Area End Here -->
        {% block content %}{% endblock %}
        <!-- Instagram Start Here -->
        {% include 'layouts/instagram_photos.html' %}
        <!-- Instagram End Here -->
        <!-- Footer Area Start Here -->
        {% include 'layouts/footer.html' %}
        <!-- Footer Area End Here -->
    </div>
    <!-- Search Box Start Here -->
    {% include 'layouts/search.html' %}
    <!-- Search Box End Here -->
    <!-- Modal Start-->
    {% include 'layouts/login_modal.html' %}
    <!-- Modal End-->
    <!-- Jquery Js -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- Bootstrap Js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap Js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins Js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Owl Carousel Js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- Smoothscroll Js -->
    <script src="{% static 'js/smoothscroll.min.js' %}"></script>
    <!-- Custom Js -->
    <script src="{% static 'js/main.js' %}"></script>
    {% block extra %}{% endblock %}
</body>


</html>

templates/layouts/footer.html
{% load static %}
<footer class="ranna-bg-dark">
            <div class="container">
                <div class="footer-logo">
                    <a href="index.html"><img src="{% static 'img/logo-light.png' %}" class="img-fluid" alt="footer-logo"></a>
                </div>
                <div class="footer-menu">
                    <ul>
                        <li><a href="#">FACEBOOK</a></li>
                        <li><a href="#">TWITTER</a></li>
                        <li><a href="#">INSTAGRAM</a></li>
                        <li><a href="#">PINTEREST</a></li>
                        <li><a href="#">GOOGLEPLUS</a></li>
                        <li><a href="#">YOUTUBE</a></li>
                    </ul>
                </div>
                <div class="copyright"><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></div>
            </div>
        </footer>

templates/layouts/instagram_photos.html
{% load static %}
<section class="instagram-feed-wrap">
            <div class="instagram-feed-title"><a href="#"><i class="fab fa-instagram"></i>Follow On Instagram</a></div>
            <ul class="instagram-feed-figure">
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure1.jpg' %}" alt="Social"></a>
                </li>
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure2.jpg' %}" alt="Social"></a>
                </li>
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure3.jpg' %}" alt="Social"></a>
                </li>
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure4.jpg' %}" alt="Social"></a>
                </li>
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure5.jpg' %}" alt="Social"></a>
                </li>
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure6.jpg' %}" alt="Social"></a>
                </li>
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure7.jpg' %}" alt="Social"></a>
                </li>
                <li>
                    <a href="single-recipe1.html"><img src="{% static 'img/social-figure/social-figure8.jpg' %}" alt="Social"></a>
                </li>
            </ul>
        </section>

templates/layouts/login_modal.html
{% load static %}
<div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="title-default-bold mb-none">Login</div>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form class="login-form">
                        <input class="main-input-box" type="text" placeholder="User Name" />
                        <input class="main-input-box" type="password" placeholder="Password" />
                        <div class="inline-box mb-5 mt-4">
                            <div class="checkbox checkbox-primary">
                                <input id="modal-checkbox" type="checkbox">
                                <label for="modal-checkbox">Remember Me</label>
                            </div>
                            <label class="lost-password"><a href="#">Lost your password?</a></label>
                        </div>
                        <div class="inline-box mb-5 mt-4">
                            <button class="btn-fill" type="submit" value="Login">Login</button>
                            <a href="#" class="btn-register"><i class="fas fa-user"></i>Register Here!</a>
                        </div>
                    </form>
                    <label>Login connect with your Social Network</label>
                    <div class="login-box-social">
                        <ul>
                            <li><a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" class="linkedin"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#" class="google"><i class="fab fa-google-plus-g"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/layouts/search.html
{% load static %}
<div id="search" class="search-wrap">
        <button type="button" class="close">×</button>
        <form class="search-form">
            <input type="search" id="ooooo" value="" placeholder="Type here........" />
            <button type="submit" class="search-btn"><i class="flaticon-search"></i></button>
        </form>
    </div>

templates/pages/about.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
    <!-- Inne Page Banner Area Start Here -->
    <section class="inner-page-banner bg-common" data-bg-image="{% static 'img/f' %}igure/inner-page-banner1.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumbs-area">
                            <h1>About Us</h1>
                            <ul>
                                <li>
                                    <a href="index.html">Home</a>
                                </li>
                                <li>About</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!-- Inne Page Banner Area End Here -->
    <!-- Recipe With Sidebar Area Start Here -->
    <section class="all-recipes-page-wrap padding-top-80 padding-bottom-50">
            <div class="container">
                <div class="row gutters-60">
                    <div class="col-lg-8">
                        <div class="about-box">
                            <div class="about-figure">
                                <img src="{% static 'img/f' %}igure/about2.jpg" alt="About">
                            </div>
                            <h2 class="about-title title-bar bar-center">Rosario Kareon</h2>
                            <p class="item-description">More off this less hello salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Google Recipe View. Schema.org is a collaboration byo improve the web by creatinegaera structured data markupore off this less hello salamander lied
                                    porpoise much over tightlyapedey innocuouslylife.</p>
                            <div class="section-heading heading-dark">
                                <h2 class="item-heading">QUICK CONTACT ME</h2>
                            </div>
                            <form class="about-contact-form">
                                <div class="row">
                                    <div class="col-md-4 form-group">
                                        <input type="text" placeholder="Name *" class="form-control" name="name" data-error="Name field is required"
                                            required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="col-md-4 form-group">
                                        <input type="email" placeholder="E-mail *" class="form-control" name="email" data-error="E-mail field is required"
                                            required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="col-md-4 form-group">
                                        <input type="text" placeholder="Phone *" class="form-control" name="phone"
                                            data-error="Subject field is required" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="col-12 form-group">
                                        <textarea placeholder="Message" class="textarea form-control" name="message" id="form-message"
                                            rows="7" cols="20" data-error="Message field is required" required></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="col-12 form-group mb-0 mt-3">
                                        <button type="submit" class="item-btn">SEND MESSAGE</button>
                                    </div>
                                    <div class="form-response"></div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4 sidebar-widget-area sidebar-break-md">
                        <div class="widget">
                            <div class="section-heading heading-dark">
                                <h3 class="item-heading">SUBSCRIBE &amp; FOLLOW</h3>
                            </div>
                            <div class="widget-follow-us">
                                <ul>
                                    <li class="single-item"><a href="#"><i class="fab fa-facebook-f"></i>LIKE ME ON</a></li>
                                    <li class="single-item"><a href="#"><i class="fab fa-twitter"></i>LIKE ME</a></li>
                                    <li class="single-item"><a href="#"><i class="fab fa-linkedin-in"></i>LIKE ME</a></li>
                                    <li class="single-item"><a href="#"><i class="fab fa-pinterest-p"></i>LIKE ME</a></li>
                                    <li class="single-item"><a href="#"><i class="fab fa-instagram"></i>LIKE ME</a></li>
                                    <li class="single-item"><a href="#"><i class="fab fa-youtube"></i>Subscribe</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="widget">
                            <div class="section-heading heading-dark">
                                <h3 class="item-heading">LATEST RECIPES</h3>
                            </div>
                            <div class="widget-latest">
                                <ul class="block-list">
                                    <li class="single-item">
                                        <div class="item-img">
                                            <a href="#"><img src="{% static 'img/p' %}roduct/latest1.jpg" alt="Post"></a>
                                            <div class="count-number">1</div>
                                        </div>
                                        <div class="item-content">
                                            <div class="item-ctg">DESERT</div>
                                            <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                                    Mozzarella Oelette</a></h4>
                                            <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                                    John Martin</a></div>
                                        </div>
                                    </li>
                                    <li class="single-item">
                                        <div class="item-img">
                                            <a href="#"><img src="{% static 'img/p' %}roduct/latest2.jpg" alt="Post"></a>
                                            <div class="count-number">2</div>
                                        </div>
                                        <div class="item-content">
                                            <div class="item-ctg">DESERT</div>
                                            <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                                    Mozzarella Oelette</a></h4>
                                            <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                                    John Martin</a></div>
                                        </div>
                                    </li>
                                    <li class="single-item">
                                        <div class="item-img">
                                            <a href="#"><img src="{% static 'img/p' %}roduct/latest3.jpg" alt="Post"></a>
                                            <div class="count-number">3</div>
                                        </div>
                                        <div class="item-content">
                                            <div class="item-ctg">DESERT</div>
                                            <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                                    Mozzarella Oelette</a></h4>
                                            <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                                    John Martin</a></div>
                                        </div>
                                    </li>
                                    <li class="single-item">
                                        <div class="item-img">
                                            <a href="#"><img src="{% static 'img/p' %}roduct/latest4.jpg" alt="Post"></a>
                                            <div class="count-number">4</div>
                                        </div>
                                        <div class="item-content">
                                            <div class="item-ctg">DESERT</div>
                                            <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                                    Mozzarella Oelette</a></h4>
                                            <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                                    John Martin</a></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="widget">
                            <div class="widget-ad">
                                <a href="#"><img src="{% static 'img/f' %}igure/figure4.jpg" alt="Ad" class="img-fluid"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!-- Recipe With Sidebar Area End Here -->
{% endblock %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
        <!-- Inne Page Banner Area Start Here -->
        <section class="inner-page-banner bg-common" data-bg-image="{% static 'img/figure/inner-page-banner1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumbs-area">
                            <h1>Contact With Us</h1>
                            <ul>
                                <li>
                                    <a href="index.html">Home</a>
                                </li>
                                <li>Contact</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Inne Page Banner Area End Here -->
        <!-- Contact Page Area Start Here -->
        <section class="contact-page-wrap">
            <div class="contact-box-left">
                <div class="container">
                    <div class="section-heading heading-dark">
                        <h3 class="item-heading-big">Our Address</h3>
                    </div>
                    <p>Korem ipsum dolor sitter amet consectetuer adipiscing elitter Curabt
                        ur ugueque habitant morbi tristique.</p>
                    <div class="contact-address">
                        <ul>
                            <li>
                                <div class="item-icon"><i class="fas fa-map"></i></div>
                                House #111/B, Street #05, New East NewYork City,
                                Near rebay resort -1111
                            </li>
                            <li>
                                <div class="item-icon"><i class="far fa-envelope"></i></div>
                                rannarecipes@gmail.com
                            </li>
                            <li>
                                <div class="item-icon"><i class="fas fa-phone"></i></div>
                                +123 5889 000 - 10, +123 8889 011 - 22
                            </li>
                            <li>
                                <div class="item-icon"><i class="fas fa-fax"></i></div>
                                +9856000, +9856010
                            </li>
                        </ul>
                    </div>
                    <div class="section-heading heading-dark">
                        <h3 class="item-heading-big">Send Us Message</h3>
                    </div>
                    <form id="contact-form" class="contact-form-box">
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <input type="text" placeholder="Name *" class="form-control" name="name" data-error="Name field is required"
                                    required>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-md-6 form-group">
                                <input type="email" placeholder="E-mail *" class="form-control" name="email" data-error="E-mail field is required"
                                    required>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-12 form-group">
                                <input type="text" placeholder="Subject *" class="form-control" name="subject"
                                    data-error="Subject field is required" required>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-12 form-group">
                                <textarea placeholder="Type your text" class="textarea form-control" name="message" id="form-message"
                                    rows="7" cols="20" data-error="Message field is required" required></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-12 form-group mb-0 mt-3">
                                <button type="submit" class="item-btn">SUBMIT MESSAGE</button>
                            </div>
                            <div class="form-response"></div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="contact-box-right">
                <div class="google-map-wrap-layout1">
                    <iframe src="https://maps.google.com/maps?q=-37.81618%2C%20144.95692&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed"></iframe>
                </div>
            </div>
        </section>
        <!-- Contact Page Area End Here -->
{% endblock %}

{% block extra %}
    <!-- Custom Js -->
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}